[package]
name = "zw_to_anki"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cjk = "0.2.5"
clap = { version = "4.4.6", features = ["derive"] }
genanki-rs = "0.4.0"
hsk = "0.1.0"
jieba-rs = "0.6.8"
