[package]
name = "zw_to_anki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
genanki-rs = "0.4.0"
jieba-rs = "0.6.8"
tts_rust = "0.3.5"
